services:
  byakugan:
    build: .
    container_name: byakugan
    ports:
      - "8080:5173"
      - "5000:5000"
    environment:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - CAMERA_FEED_SOURCE=${CAMERA_FEED_SOURCE:-DEFAULT}
      - BYAKUGAN_BOT_TOKEN=${BYAKUGAN_BOT_TOKEN}
      - DOCKER_HOST_IP=${DOCKER_HOST_IP}
    networks:
      - byakugan_network
    volumes:
      - sqlite_data:/app/db
      - thumbnails_data:/app/thumbnails
      - recordings_data:/app/recordings
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro       
    restart: always

networks:
  byakugan_network:
    driver: bridge

volumes:
  sqlite_data:
  thumbnails_data:
  recordings_data: