services:
  byakugan:
    build: .
    container_name: byakugan
    ports:
      - "8080:5173"
      - "5000:5000"
    environment:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - CAMERA_FEED_SOURCE=rtmp://rtmp-server/stream/test
      - BOT_TOKEN=${BOT_TOKEN}
    networks:
      - byakugan_network
    volumes:
      - sqlite_data:/app/db
      - thumbnails_data:/app/thumbnails
      - recordings_data:/app/recordings
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro       
    restart: always
      
  rtmp-server:
    image: alfg/nginx-rtmp
    container_name: rtmp-server
    ports:
      - "1935:1935"
    healthcheck:
      test: ["CMD", "netstat", "-an", "|", "grep", "1935"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - byakugan_network
    depends_on:
      - byakugan